import random

def motivation():
	mot = ["O sucesso nasce do querer, da determinação e persistência em se chegar a um objetivo. Mesmo não atingindo o alvo, quem busca e vence obstáculos, no mínimo fará coisas admiráveis.",
	"A persistência é o caminho do êxito.",
	"Determinação, coragem e autoconfiança são fatores decisivos para o sucesso. Se estamos possuídos por uma inabalável determinação, conseguiremos superá-los. Independentemente das circunstâncias, devemos ser sempre humildes, recatados e despidos de orgulho.",
	"Agir, eis a inteligência verdadeira. Serei o que quiser. Mas tenho que querer o que for. O êxito está em ter êxito, e não em ter condições de êxito. Condições de palácio tem qualquer terra larga, mas onde estará o palácio se não o fizerem ali?",
	"Lute. Acredite. Conquiste. Perca. Deseje. Espere. Alcance. Invada. Caia. Seja tudo o quiser ser, mas acima de tudo, seja você sempre.",
	"Só existe um êxito: a capacidade de levar a vida que se quer.",
	"A vitalidade é demonstrada não apenas pela persistência, mas pela capacidade de começar de novo.",
	"A coragem não é ausência do medo; é a persistência apesar do medo.",
	"Só se pode alcançar um grande êxito quando nos mantemos fiéis a nós mesmos.",
	"O homem não teria alcançado o possível se, repetidas vezes, não tivesse tentado o impossível.",
	"Todo mundo é capaz de sentir os sofrimentos de um amigo. Ver com agrado os seus êxitos exige uma natureza muito delicada."
	"Lute com determinação, abrace a vida com paixão, perca com classe e vença com ousadia, porque o mundo pertence a quem se atreve e a vida é muito para ser insignificante.",
	"Força de ânimo e coragem na adversidade servem para conquistar o êxito, mais do que um exército.",
	"Creia em si, mas não duvide sempre dos outros.",
	"Dois homens não podem passar meia hora juntos sem que um conquiste uma evidente superioridade em relação ao outro.",
	"Não deixe que as pessoas te façam desistir daquilo que você mais quer na vida. Acredite. Lute. Conquiste. E acima de tudo, seja feliz!",
	"As únicas grandes companhias que conseguirão ter êxito são aquelas que consideram os seus produtos obsoletos antes que os outros o façam.",
	"Talento é dom, é graça. E sucesso nada tem a ver com sorte, mas com determinação e trabalho.",
	"Para ter um negócio de sucesso, alguém, algum dia, teve que tomar uma atitude de coragem.",
	"Nenhum mentiroso tem uma memória suficientemente boa para ser um mentiroso de êxito.",
	"Estar decidido, acima de qualquer coisa, é o segredo do êxito.",
	"Para obter êxito no mundo temos de parecer loucos mas sermos espertos.",
	"A disciplina é a mãe do êxito.",
	"O segredo do êxito na vida de um homem está em preparar-se para aproveitar a ocasião, quando ela se apresenta.",
	"O êxito começa no exato momento em que o homem decide o que quer e começa a trabalhar para consegui-lo.",	
	"A disciplina é a alma de um exército; torna grandes os pequenos contingentes, proporciona êxito aos fracos, e estima todos.",	
	"A raiz do mal reside no fato de se insistir demasiadamente que no êxito da competição está a principal fonte de felicidade.",	
	"O êxito parece doce a quem não o alcança.",	
	"A persistência realiza o impossível.",	
	"Persistência é a irmã gêmea da excelência. Uma é a mãe da qualidade, a outra é a mãe do tempo.",	
	"Eu escolho um homem que não duvide de minha coragem, que não me acredite inocente, que tenha a coragem de me tratar como uma mulher.",	
	"Ai daqueles que pararem com sua capacidade de sonhar, de invejar sua coragem de anunciar e denunciar. Ai daqueles que, em lugar de visitar de vez em quando o amanha pelo profundo engajamento com o hoje, com o aqui e o agora, se atrelarem a um passado de exploração e de rotina.",	
	"Suba o primeiro degrau com fé. Não é necessário que você veja toda a escada. Apenas dê o primeiro passo.",	
	"Você tem que acordar cada manhã com determinação se você pretende ir para a cama com satisfação.",	
	"As pessoas não carecem de força, carecem de determinação.",	
	"A verdadeira esperança é uma qualidade, uma determinação heroica da alma. E a mais elevada forma de esperança é o desespero superado.",	
	"Conserve os olhos fixos num ideal sublime, e lute sempre pelo que deseja, pois só os fracos desistem e só quem luta é digno de vida.",	
	"A esperança não será a prova de um sentido oculto da Existência., uma coisa que merece que se lute por ela?",	
	"O êxito da vida não se mede pelo caminho que você conquistou, mas sim pelas dificuldades que superou no caminho.",	
	"A impaciência é um grande obstáculo para o bom êxito.",
	"Não procure ser um homem com êxito, e sim um homem com valores.",	
	"O êxito é fácil de obter. O difícil é merecê-lo.",	
	"O êxito na vida não significa apenas ser bem sucedido, mas também sobrepor-se aos fracassos.",	
	"Tudo deveria se tornar o mais simples possível, mas não simplificado.",	
	"Comece fazendo o que é necessário, depois o que é possível, e de repente você estará fazendo o impossível.",
	"O erro acontece de vários modos, enquanto ser correto é possível apenas de um modo.",	
	"Não é possível ser bom pela metade.",	
	"O milagre não prova o impossível; serve, apenas, como confirmação do que é possível.",	
	"As pessoas que resolviam as coisas em geral tinham muita persistência e um pouco de sorte. Se a gente persistisse o bastante, a sorte em geral chegava. Mas a maioria das pessoas não podia esperar a sorte, por isso desistia.",	
	"Tudo o que um sonho precisa para ser realizado é alguém que acredite que ele possa ser realizado.",	
	"A nossa maior glória não reside no fato de nunca cairmos, mas sim em levantarmo-nos sempre depois de cada queda.",	
	"Transportai um punhado de terra todos os dias e fareis uma montanha.",	
	"Seja como os pássaros que, ao pousarem um instante sobre ramos muito leves, sentem-nos ceder, mas cantam! Eles sabem que possuem asas.",	
	"A força não provém da capacidade física. Provém de uma vontade indomável.",	
	"O número dos que nos invejam confirma as nossas capacidades.",	
	"Nas pessoas de capacidade limitada, a modéstia não passa de mera honestidade, mas em quem possui grande talento, é hipocrisia.",	
	"É capaz quem pensa que é capaz.",	
	"Quem sabe concentrar-se numa coisa e insistir nela como único objetivo, obtém a capacidade de fazer qualquer coisa.",	
	"O ser capaz mora perto da necessidade.",
	"A capacidade pouco vale sem oportunidade.",	
	"Acredite em si próprio e chegará um dia em que os outros não terão outra escolha senão acreditar com você.",	
	"Se a sua vida for a melhor coisa que já te aconteceu, acredite, você tem mais sorte do que pode imaginar.",	
	"Quer você acredite que consiga fazer uma coisa ou não, você está certo.",	
	"Acredite em si. Engate a mente na sua boa estrela e reconheça que a sua luz interior o conduzirá sempre para cima e para a frente.",	
	"Ninguém é assim tão velho que não acredite que poderá viver por mais um ano.",	
	"Gostaria que você soubesse que existe dentro de si uma força capaz de mudar sua vida. Basta que lute e aguarde um novo amanhecer.",	
	"Jamais desista das pessoas que ama. Jamais desista de ser feliz. Lute sempre pelos seus sonhos. Seja profundamente apaixonado pela vida. Pois a vida é um espetáculo imperdível.",	
	"Ame mesmo que isso cause sofrimento, mesmo que todo mundo fale para desistir. Lute pelo que você quer.",	
	"Maravilhas nunca faltaram ao mundo; o que sempre falta é a capacidade de senti-las e admirá-las.",
	"Deus, ao criar o homem, superestimou a Sua capacidade.",
	"Inteligência é a capacidade de se adaptar à mudança.",
	"Capacidade de saber cada vez mais sobre cada vez menos, até saber tudo sobre nada.",
	"O amor é a arte de criar algo com a ajuda da capacidade do outro.",
	"A liderança é a capacidade de conseguir que as pessoas façam o que não querem fazer e gostem de o fazer.",
	"Tato é a capacidade de se descrever os outros tal como eles se julgam.",
	"A sabedoria dos homens é proporcional não à sua experiência, mas à sua capacidade de adquirir experiência.",
	"Pensamento duplo indica a capacidade de ter na mente, ao mesmo tempo, duas opiniões contraditórias e aceitar ambas.",
	'Sua luta não termina quando sentir cansaço, mas sim quando atingir o sucesso tão merecido.', 
	'Não perca a motivação só porque as coisas não estão correndo como o previsto. Adversidade gera sabedoria e é isso que levará você ao sucesso.', 
	'Às vezes um pouco de motivação ajuda a superar os maiores desafios.', 
	'Arrisque, vá em frente e sem medo! Não há motivação maior do que descobrir quão corajosos conseguimos ser.', 
	'Há motivação maior na vida do que aquele amanhecer cheio de luz e esperança a entrar pela janela? Viver é uma experiência única e fascinante.', 
	'Só você pode determinar suas limitações, por isso não desista mesmo que tudo pareça perdido.', 
	'Acreditar é a força que nos permite subir os maiores degraus na escada da vida.', 
	'Se ao enfrentar os problemas da vida lhe parecer que está escalando uma montanha impossível, lembre-se que a paisagem que avistará no topo compensará qualquer esforço seu.', 
	'O poder está dentro de você, na sua mente, pois se acreditar que consegue não haverá obstáculo capaz de impedir o seu sucesso.', 
	'A vida tanto lhe pode dar o melhor como o pior, mas é você quem escolhe aquilo que vai permanecer ou ficar para trás.', 
	'Teste os seus limites, enfrente os seus medos e não deixe que nada impeça você de pelo menos tentar!', 
	'Você é mais forte e mais capaz do que imagina, e a conquista dos seus objetivos depende apenas de você!', 
	'Aquilo que você está vivendo, o peso que você está carregando, não é nada comparado à alegria que está esperando por você!', 
	'Sempre que algo falhar, batalhe ainda mais forte até encontrar empenho novamente!', 
	'Tudo que você precisa para começar a realizar seus sonhos é confiar em você, e lutar sem ter medo de falhar.', 
	'Não desista já, pois o caminho que leva ao sucesso tem várias etapas e inclui alguns obstáculos!', 
	'Na vida o que realmente vale a pena demora e custa a alcançar, por isso não desista à primeira dificuldade.', 
	'Serei sempre otimista, pois acreditar é o primeiro passo para fazer acontecer!', 
	'Acredite que você pode ser como uma árvore forte que se mantém de pé até nas maiores tempestades.', 
	'Trabalhe por uma causa, e não por aplausos. Trabalhe para expressar o melhor de você, e não para impressionar.', 
	'Neste jogo da vida o maior vencedor é aquele que luta até ao fim.', 
	'Se você não arriscar nunca irá saber até onde é capaz de chegar!', 
	'Se é difícil é porque vale a pena e um dia pode ser maravilhoso.', 
	'Desistir é para os fracos ou para quem já não acredita mais no impossível!', 
	'Fique tranquilo! Amanhã você vai achar um jeito de sorrir daquilo que hoje lhe fez chorar.', 
	'Acredite nas suas capacidades e lute todos os dias para que elas sobressaiam no seu trabalho.', 
	'Não deixe que seus sonhos percam a força de voar!', 
	'Jamais desista, pois até as flores mais devastadas pela tempestade acabam sempre por renascer na primavera.', 
	'Neste mundo nem todas as possibilidades se concretizam, mas a de ser feliz está perfeitamente ao alcance das suas mãos.', 
	'O único homem que nunca comete erros é aquele que nunca faz coisa alguma. Não tenha medo de errar, pois você aprenderá a não cometer o mesmo erro duas vezes.', 
	'Não ceda à vontade de desistir; não desperdice todo o caminho que já percorreu e todas as oportunidades que ainda vão surgir!', 
	'Pense positivo, concentre-se no que é bom e lhe faz bem, e tenha uma memória seletiva para esquecer aquilo que lhe faz mal.', 
	'O importante na luta não é vencer e sim lutar.', 
	'Derrotado hoje e vencedor amanhã; esse é o espírito de quem vai triunfar na vida!', 
	'Lembre-se que apesar das derrotas e perdas a vida ainda tem muito de bom para lhe dar.', 
	'Não falta quem faça planos, mas para a história apenas ficam aqueles que os concretizaram.', 
	'Porque a vida é uma prova de fogo, encare cada batalha com amor no coração!', 
	'Após mil quedas eu estarei de pé após me levantar mil vezes!', 
	'Porque na vida não existem limites ou condições dê a volta por cima em todas as situações!', 
	'A alegria de viver não está presente na vida, mas no modo como a encaramos!', 
	'Nunca deixe que nenhum limite tire de você a ambição da auto-superação.', 
	'Se queres ser feliz amanhã, tenta hoje mesmo.', 
	'A força de vontade fica quietinha cochilando dentro de você, mas quando os seus sonhos começarem a falar mais alto, ela acorda.', 
	'Nada é impossível para quem tem ambição de vencer.', 
	'Trabalhar duro pode nem sempre garantir o sucesso, mas fazer menos que isso garante o insucesso.', 
	'Sorte é o que acontece quando a preparação encontra a oportunidade.', 
	'Saber viver é difícil, às vezes dói, custa, mas enquanto lutarmos, estamos mais próximos das grandes conquistas.', 
	'Não permita que os seus pensamentos fiquem na imaginação por muito tempo, pois o que alimenta as nossas vontades são os verdadeiros acontecimentos!', 
	'Não permita que uma derrota desvie seus passos do caminho até ao sucesso.', 
	'Em equipe tudo se descomplica, tem mais valor, ganha outro interesse.', 
	'Não ceda ao medo, ao fracasso, ao preconceito. Você é forte, vai superar tudo e em breve a vitória será sua!', 
	'Seja qual for a dificuldade do caminho, atravesse-o com ânimo e coragem para se superar e alcançar a sua meta.', 
	'Acredito que sou capaz, sei quanto vale minha coragem. Na verdade, superar dificuldades é um divertimento para mim!', 
	'Não desista, tenha fé e deixe o tempo agir para tudo melhorar!', 
	'Você tem tudo que precisa para conquistar seus sonhos, basta ter determinação e coragem para tentar!', 
	'Você está destinada a chegar aonde quiser e a realizar sonhos incríveis, por isso vá em frente. Força!', 
	'Encontre força no seu interior e coloque para fora toda a garra e determinação que você possui!', 
	'Precisamos ser fortes, precisamos ter coragem! Juntos, venceremos!', 
	'Não procure forças no céu ou ao seu redor, mas sim no seu interior. Você pode tudo! Acredite.', 
	'Nunca duvide porque sua força vem de Deus.', 
	'Não encare as dificuldades como problemas, mas como desafios ainda não superados.', 
	'Não importa como nem em que condições, mas sim que acredite e se esforce para que aconteça. Realize seus sonhos!', 
	'O primeiro passo é acreditar em si mesmo.', 'O seu coração irá levar você na direção certa sempre!', 
	'Obstáculos existem a toda hora, mas eu tudo farei para os superar, um após outro até chegar onde quero!', 
	'Se não tentar, não falha, mas também não há chance de acertar.', 'A verdadeira derrota é nem sequer tentar.', 
	'Se existe um problema, de certeza que há uma solução para ele.', 'Correr atrás é sempre a melhor forma de conseguir.', 
	'É nas pequenas coisas da vida que encontro motivação para seguir lutando.', 
	'Foco, força e fé geram verdadeira motivação para que nada nos faça desistir dos nossos maiores sonhos.', 
	'Neste início de aulas, que a motivação seja a maior de sempre, e que ela venha acompanhada por uma grande vontade de aprender.', 
	'A curiosidade em saber o que o futuro nos reserva é a maior motivação para sempre seguirmos em frente.',
	'A força de vontade é o leme que conduz a nossa vida e nos faz navegar em busca de nossos sonhos.', 'A força de vontade fica mais forte quando temos foco, determinação e capacidade de ação.', 'As melhores coisas da vida são aquelas que lutamos para conquistar. Com força de vontade conseguimos tudo.', 'É bom ter força de vontade, mas é melhor ter atitude.', 'Faça da força de vontade seu estilo de vida e prepare-se para dias de sucesso, conquistas e muitas glórias!', 'Os problemas não assustam aquele que tem força de vontade para os resolver!', 'Não há vencedores sem esforço, nem recompensas conquistadas sem espírito de sacrifício.', 'Foco, força e fé geram verdadeira motivação para que nada nos faça desistir dos nossos maiores sonhos.', 'Tenha sempre coragem para arriscar, pois pior que não conseguir é perder por nunca ter tentado!', 'Que a força nunca seja demais, o foco de menos e a fé esteja sempre inabalável!', 'Foco para realizar, força para levantar depois da queda e fé para acreditar no impossível!', 'Sorrio sempre, porque tenho fé na força que o Senhor me dá para alcançar a paz e a felicidade!', 'A palavra “impossível” não entra no vocabulário de quem acredita, tem força e fé.', 'Ter fé em suas capacidades e força para encarar os desafios é o mais importante para alcançar qualquer objetivo.', 'Aceito todos os desafios da vida com força para os combater e fé para os superar.', 'Não abdique da sua fé para que nunca lhe falta força para lutar por aquilo em que acredita.', 'Eu não sou pessoa de desistir à primeira tentativa, pois acredito que as maiores bênçãos estão guardadas para quem se esforça em lutar.', 'Mesmo que o caminho seja difícil de percorrer, com determinação tudo será alcançado.', 'Passar das palavras aos atos é tudo uma questão de atitude!', 'Às vezes a única solução é ser forte e suportar com integridade todos os desafios que a vida nos colocou pela frente.', 'Aceite meu ombro amigo e saiba que pode sempre contar comigo nos momentos mais difíceis. Estou com você hoje e sempre que precisar.', 'Se está muito difícil encontrar o caminho, faça-o.', 'Busco na minha fé forças para fazer de todas as situações uma oportunidade de aprendizado e crescimento.', 'Quando existe fé tudo de bom pode acontecer e nada será impossível de realizar.', 'A fé nos dá forças que, por vezes, não sabíamos que tínhamos dentro de nós.', 'Muitas vezes encontramos a coragem no lugar mais improvável, mas não podemos perder de forma alguma a perseverança, pois só assim ganhamos força suficiente para superar qualquer dificuldade.', 'Reclamar ou desistir não resolve os seus problemas, mas a força sim se for acompanhada da coragem.', 'Tia, agradeço muito pela sua amizade e por ser para mim um exemplo de força, coragem e determinação.', 'Algumas vezes na vida a única coisa de que precisamos é de alguns segundos de otimismo, e de uma coragem insana para correr atrás daquilo que sonhamos!', 'Acreditar é a força que nos permite subir os maiores degraus na escada da vida.', 'Os meus sonhos não têm distância; eles estão sempre perto da minha força de vencer.', 'Se ao enfrentar os problemas da vida lhe parecer que está escalando uma montanha impossível, lembre-se que a paisagem que avistará no topo compensará qualquer esforço seu.', 'Minha filha, meu bem mais precioso, cada dia que passo ao seu lado é uma bênção, pois me faz descobrir a força do amor que nos une.', 'Acredite sempre, mesmo que o Sol não esteja brilhando, porque a força de acreditar é capaz de destruir a escuridão.', 'Não adianta acreditar se você não tem coragem de lutar.', 'É nos piores momentos que você tem oportunidade de mostrar a força das suas convicções e a grandeza da sua atitude!', 'Nenhum esforço é em vão; sua luta será sempre minha grande inspiração. Feliz Dia das Mães!', 'Posso não ser o melhor pai, mas eu juro que tento e me esforço todos os dias para fazer você feliz. Te adoro, filha!', 'A maior dor do amor é quando sabemos que ele deve morrer, mas não temos coragem de matá-lo.', 'Quando a vida tentar derrubar você contrarie essa vontade mantendo o otimismo e assim continuando de pé!', 'Ser mulher é amar com toda doçura, assim como lutar com toda bravura. É ser sensível e quando necessário uma força brutal da natureza!', 'Bom dia, meu amor! Saber que tenho você do meu lado me dá força para enfrentar o mundo todos os dias.', 'Meu coração implora que eu ganhe coragem para parar de mentir falando que só quero sua amizade!', 'Às vezes é preciso passar por certas dificuldades para que possamos enfrentar com mais força o que virá pela frente!', 'Hoje acordei com vontade de te ver, de te tocar e de te beijar, mas como estas longe fico apenas pelo desejar!', 'Podemos tudo que nossa vontade quiser, pois não é o gênero que nos define, mas a pessoa que somos ou queremos vir a ser. Feliz dia da Mulher!', 'Dia após dia os erros do passado perdem força e os desejos do futuro ganham corpo.', 'A diferença entre a mulher fraca e a mulher forte é que a primeira ainda não descobriu a força que tem.', 'Tenho um mundo inteiro para descobrir e uma vontade incessante de o conquistar.', 'Sempre que sentir vontade de desistir lembre-se que seus sonhos podem ser alcançados no próximo passo que der.', 'Os seus medos e problemas não passam de provas de fogo prontas a serem apagadas pela sua coragem e determinação.', 'Eu sei que terminou, mas às vezes o coração aperta e dá vontade de correr para os braços de quem amamos.', 'Beijo na testa è sinal de carinho e no queixo è vontade de subir mais um pouquinho.', 'O sucesso depende tanto do esforço como da atitude certa para fazer acontecer!', 'Podemos não ter a relação perfeita ou as ações mais corretas, mas ficaremos juntos para sempre porque temos uma união de ferro!', 'É preciso coragem para tomar as decisões certas. 💪', 'Não ceda à vontade de desistir; não desperdice todo o caminho que já percorreu e todas as oportunidades que ainda vão surgir!', 'Eu acredito em você e na sua capacidade porque conheço o seu esforço e a sua motivação. Não desista!', 'Depois da recuperação, você será uma nova pessoa. Mais forte, mais sábia e com mais vontade de ser feliz!', 'Não precisamos ter tudo; basta um pouco de fé para acreditarmos nos nossos sonhos e força para lutarmos por eles. Bom dia!', 'Nossa força está refletida no modo como nos levantamos depois de uma queda.', 'O desprezo que eu sinto por você só é menor que a vontade que eu tenho que você suma da minha vida.', 'Nem sempre podemos sorrir e estar felizes, às vezes surge uma tristeza, uma lágrima para testar nossa coragem.', 'Mãe, você é meu maior exemplo de força e quando eu crescer quero ser exatamente como você!', 'Limpe o suor, levante a cabeça e solte uma risada porque é do esforço que vêm as grandes recompensas.', 'Com todas as suas palavras sábias e ações bondosas, Jesus nos deixou um modelo perfeito para seguirmos de perto.', 'Dê o seu máximo sem medo da derrota, porque fracasso é no final da batalha ter consciência que com mais um pouco de esforço poderia ter vencido.', 'O que mais faço na vida é passar vontade, olhando para este sorriso lindo do meu crush!', 'Sempre que caí recorri à vontade de aprender e a cada queda me tornei mais sábia!', 'A força da mulher não vem dos músculos, vem da persistência e da resiliência que precisam para vencer na vida.', 'Sou uma mulher poderosa porque me conheço muito bem e sei da força que carrego dentro do meu peito.', 'Pedir desculpa é muito mais do que assumir um erro: é expressar a vontade de não cometer esse erro outra vez.', 'Quando o sonho for grande demais renda-se à vontade de vencer!', 'Ainda tem dúvidas se as mulheres são fortes? Então olhe para sua vida e veja como você é dependente da força delas.', 'As minhas vitórias serão sempre fruto do esforço de uma equipe inteira que se ajuda, apoia e não desiste.', 'Nosso amor é perfeito; é a luz que me ilumina e aquece, é a paz que elimina meus tormentos e a força para todas as minhas lutas.', 'Não subestime a força do seu pensamento, use-o sempre como um aliado contra qualquer sofrimento.', 'Que cada lágrima liberada no luto seja revertida em força para continuar de pé nos próximos dias.', 'Quem critica a injustiça o faz não porque teme cometer ações injustas, mas porque teme sofrê-las.', 'É na aflição que surge aquela força capaz de transformar uma prova de fogo em superação.', 'Saiba que seu desprezo só me dá mais vontade de ser ainda melhor.', 'A família deveria ser vista como um grupo de pessoas unido pela mesma vontade de manter um bom relacionamento todos os dias.', 'Seja mulher, seja poderosa e torne-se um exemplo para quem precisa de força!', 'Se o sucesso tardar não se revolte com o mundo, mas encha-se de coragem e lute com mais determinação.', 'Os momentos difíceis já não são mais intransponíveis pois tenho a força do seu amor para me ajudar a superá-los. Agradeço por ter você, meu amor!', 'Arrepender-se das boas ações é sacrificar a consciência ao egoísmo da paixão.', 'A maneira de se conseguir boa reputação reside no esforço em se ser aquilo que se deseja parecer.', 'Não deixe que o fracasso elimine a vontade de superação, pois muitas vezes a derrota aparece para evidenciar um mesmo erro que se repete.', 'A graça é uma qualidade que dá ao homem a força de executar as exigências da lei.', 'Sinto muito, mas a inspiração nunca chega primeiro do que o esforço.', 'As mulheres são sempre poderosas, mas uma mulher decidida e focada em um objetivo é uma força que não há como parar.', 'A coragem só aparece quando ter medo já não é uma escolha acessível.', 'Pode ser muito difícil desapegar daquilo que nos faz mal, mas a sensação de liberdade certamente compensa todo o esforço no final.', 'A força gerada pela não violência é infinitamente maior do que a força de todas as armas inventadas pela engenhosidade do homem.', 'Por menores que sejam suas ações elas podem ter um impacto permanente e gigantesco. Reflita sobre suas atitudes e tenha um bom dia!', 'Nada é impossível se você tiver foco no seu objetivo e coragem no seu coração!', 'Feliz dia do homem para todos aqueles que celebram a vida com a força do coração!', 'Com coragem, em cada instante surge uma nova chance de viver uma nova vida!', 'Seja forte, tenha coragem e lembre-se que estarei ao seu lado sempre. Sinto muito pela sua perda.', 'Não espero presentes da sorte, mas luto para receber recompensas do esforço.', 'Nos teus olhos encontrei a verdadeira inspiração e a força para viver.', 'Você pode pensar que suas ações não têm consequências, mas cuidado, pode até demorar, mas o carma não costuma perdoar.', 'Prepare o café, pois a semana só está começando e ainda tem muita coisa para acontecer! Coragem!', 'Nunca é fácil se despedir de alguém especial. Desejo força e fé para você neste momento difícil. Sinto muito.', 'Às vezes começa com um sorriso e que logo contagia seu coragem e o enche de alegria para viver.', 'As pernas mexem sem eu mandar, a vontade de gritar amor ao mundo é cada vez maior. Assim é a alegria de viver! Assim é o Carnaval!', 'Não há mal nenhum em recomeçar, é preciso ter muita coragem para conseguir ultrapassar a fase do tentar.', 'Acredito que sou capaz, sei quanto vale minha coragem. Na verdade, superar dificuldades é um divertimento para mim!', 'A força do Homem não se define pela sua capacidade física, mas sim na fé e confiança em algo maior!', 'A força de uma mulher não é uma coisa que nós conseguimos ver com os olhos, é algo que se sente no âmago do nosso ser.', 'Neste começo lute com mais força para alcançar ainda mais metas e objetivos. Feliz Ano Novo!', 'A verdade é que meu coração se parte em mil pedaços quando penso em tudo que quis fazer, mas não tive coragem.', 'Mães, vocês são a maior força do mundo e o motivo pelo qual nós sempre tentamos ser motivo de orgulho.', 'Primeiro apure os fatos. Depois, pode distorcê-los à vontade.', 'Não temo as dificuldades, porque só elas me fortalecem e enchem de coragem para os grandes desafios da vida!', 'A força das mães está na capacidade de serem duras e fortes sem perder a ternura e o amor que guardam nos seus corações.', 'O mundo ficou um pouco mais cinzento hoje. Meus pêsames e muita força neste momento tão delicado.', 'Quero parabenizar e dar muita força a todos os enfermeiros pela luta constante contra a doença e pela ajuda que prestam aos nossos doentes.', 'Dentro de você existe uma força que desconhece e que é capaz de levar você a superar qualquer obstáculo.', 'Você tem tudo que precisa para conquistar seus sonhos, basta ter determinação e coragem para tentar!', 'Só amar vale a pena, dar e receber, sem medo nem preconceito. O amor é ter coragem de viver!', 'O descanso chegou e com ele a vontade de passar o dia nos teus braços. Bom domingo, amor!', 'Ajudo porque tenho prazer nisso, mas se quiser ser recíproco, por favor, faça-o por vontade e não por obrigação.', 'Você está destinada a chegar aonde quiser e a realizar sonhos incríveis, por isso vá em frente. Força!', 'Quando alguém se despede deixa sempre um vazio na vida daqueles que ficam. Desejo muita força para que você possa suportar a sua perda.', 'Fantasmas à solta, bruxas em casa esquina! Ninguém sabe o que o Halloween nos reserva, só sabemos que é preciso coragem para viver esta noite!', 'As alegrias engrandecem meu coração, as quedas fortalecem minha coragem.', 'Um sonho só se torna realidade se você tem coragem de não desistir dele.', 'Vou guardar essa foto no celular para ver sempre que tiver vontade de rir. 😂', 'Não há sociedade que pare a força de uma mulher determinada a lutar pela justiça e igualdade.', 'Não há beleza nem força maior que a natureza. Cuidando dela cuido de mim.', 'Acordei e é como se eu não tivesse dormindo de tanta falta de vontade de levantar. Bom dia!', 'Seus pensamentos têm de estar em total harmonia com suas ações para conseguir sentir verdadeira paz no coração.', 'É sempre necessário que nossas ações estejam de acordo com os nossos princípios. Só assim seremos totalmente honestos.', 'Você é exemplo de força e determinação e tenho muito orgulho de tê-lo como meu avô!', 'Irmãos brigam com a mesma força e a mesma intensidade com que se amam.', 'Todos os pequenos gestos contam na hora de proteger o meio ambiente, nem sempre são necessárias grandes medidas ou ações.', 'Meus sentimentos. Eu estou ainda em choque pela sua perda. Seja forte e tenha coragem.',
	
	
	]
	return mot

def emoji():
	# ☺ ✌
	em = [':)',':D',';)','B|','<3','^_^',':*',':v','(y)']
	return em
 
t = motivation()
#print(f'"{random.choice(motivation())}" Bot motivacional {random.choice(emoji())}')